language: python
python:
- '2.7'
script:
- sudo apt-get install python-dev -y
- pip install -r requirements.txt
- pip install python-Levenshtein
- ls ~/virtualenv/python2.7/lib/python2.7/site-packages
